// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDanHajlF4hizepbsIJtJAraFxoZRjStWs',
    appId: '1:862281581463:web:c99ae2e83d07e7fca77ad2',
    messagingSenderId: '862281581463',
    projectId: 'todo-flutter-86432',
    authDomain: 'todo-flutter-86432.firebaseapp.com',
    storageBucket: 'todo-flutter-86432.appspot.com',
    measurementId: 'G-E9C3GYB1DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn7J4dSFW7tKrCDIeXHIvZzfp1M9iZQYU',
    appId: '1:862281581463:android:345add94c08682d3a77ad2',
    messagingSenderId: '862281581463',
    projectId: 'todo-flutter-86432',
    storageBucket: 'todo-flutter-86432.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmtr86rai4HjMEt8TSY3Q2Fwpl3b6D2J8',
    appId: '1:862281581463:ios:471972e430d1213da77ad2',
    messagingSenderId: '862281581463',
    projectId: 'todo-flutter-86432',
    storageBucket: 'todo-flutter-86432.appspot.com',
    androidClientId: '862281581463-68ou00f9ek68qf3eo0armca8a40nith5.apps.googleusercontent.com',
    iosClientId: '862281581463-qff21pcsp7ugnt4egvq7upvn8ib2eqbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.apps5CrudFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmtr86rai4HjMEt8TSY3Q2Fwpl3b6D2J8',
    appId: '1:862281581463:ios:471972e430d1213da77ad2',
    messagingSenderId: '862281581463',
    projectId: 'todo-flutter-86432',
    storageBucket: 'todo-flutter-86432.appspot.com',
    androidClientId: '862281581463-68ou00f9ek68qf3eo0armca8a40nith5.apps.googleusercontent.com',
    iosClientId: '862281581463-qff21pcsp7ugnt4egvq7upvn8ib2eqbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.apps5CrudFirestore',
  );
}
